# Generated by Django 4.0.4 on 2022-05-09 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('series', models.CharField(max_length=50, verbose_name='Серия')),
                ('year', models.IntegerField(verbose_name='Год выпуска')),
                ('age', models.IntegerField(verbose_name='Возрастная группа')),
                ('size', models.CharField(max_length=50, verbose_name='Серия')),
                ('exclusive', models.BooleanField(verbose_name='Эксклюзив')),
                ('new', models.BooleanField(verbose_name='Новинка')),
                ('quantity', models.IntegerField(verbose_name='Количество деталей')),
                ('price', models.IntegerField(verbose_name='Цена')),
            ],
        ),
    ]
