# Generated by Django 4.0.4 on 2022-05-28 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lego',
            name='series',
        ),
        migrations.RemoveField(
            model_name='lego',
            name='year',
        ),
    ]
